[package]
name = "scratchpad"
version = "0.1.0"
authors = ["user"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"

[[bin]]
name = "scratchpad"
path = "src/main.rs"

rand = "0.7.3"
